#!/bin/bash
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --time=00:10:00
#SBATCH --job-name=dedalus
#SBATCH --output=dedalus_output_%j
####SBATCH --mail-type=begin
####SBATCH --mail-type=end
####SBATCH --mail-user=chli3324@colorado.edu
export SLURM_EXPORT_ENV=ALL
#export I_MPI_FABRICS=shm,tcp

##the slurm number to restart simulation... This need full state to be stored.
SUBMITDIR=$SLURM_SUBMIT_DIR
WORKDIR=/scratch/chl23026/chl23026/dedalus_$SLURM_JOB_ID
mkdir -p "$WORKDIR" && cp -r dedalus*.py "$WORKDIR" && cp submit_dedalus "$WORKDIR" && cd "$WORKDIR" || exit -1

###uncomment this line and change the folder number to select which simulation to restart
#ln -s /projects/chli3324/dedalus_main/IC/2D_tau_0p01_Ra_S2T_2500_Pr_0p05_kx_12/HB_benard_shear_analysis_s1_Nz128_tr_bpt1_Lx2d_1.h5 restart.h5
#ln -s /projects/chli3324/dedalus_main/IC/periodic_2D_tau_0p01_Ra_S2T_2500_Pr_7_kx_18/periodic_analysis_s1_Nx128_Nz128_tr_bpt1_last_pt_last_pt_p_ds_Lx2d_1.h5 restart.h5
#ln -s /projects/chli3324/dedalus_main/IC/flux_T_periodic_RBC_kx_2pi_Ra_T_20000/flux_T_periodic_analysis_s1_Nx128_Nz128_tr_bpt1_bpt1_Lx2d_1.h5 restart.h5
#ln -s /projects/chli3324/dedalus_main/IC/stress_free_2D_tau_0p01_Ra_S2T_2500_Pr_7_kx_14/analysis_s1_Nx256_Nz256_tr_bpt1_Lx2d_1.h5 restart.h5
#ln -s /projects/chli3324/dedalus_main/IC/tau_0p01_Ra_S2T1500/analysis_s1_Nx64_Nz128tr_bpt1.h5 restart.h5

#####Update 2023/06/06 IC from 2D continuation.
#ln -s /projects/chli3324/dedalus_main/IC/periodic_MM_tau_R_rho_40_Ra_T_1e5_tau_0p01_Pr_7_kx_18/periodic_analysis_s1_Nx128_Nz128_tr_bpt1_last_pt_last_pt_p_ds_Lx2d_1.h5 restart.h5

#ln -s /projects/chli3324/dedalus_main/analysis_s1.h5 restart.h5
#ln -s /rc_scratch/chli3324/dedalus_13209996/analysis/analysis_s1.h5 restart.h5
#ln -s /rc_scratch/chli3324/dedalus_12808427/analysis/analysis_s1.h5 restart.h5
#ln -s /rc_scratch/chli3324/dedalus_13146434/analysis/analysis_s1.h5 restart.h5
#ln -s /rc_scratch/chli3324/dedalus_13146434/checkpoint/checkpoint_s1.h5 restart.h5

conda activate dedalus2

##For IVP simulation
mpiexec -n $SLURM_NTASKS python3 dedalus_main.py

cd "$SUBMITDIR" && cp dedalus_output_$SLURM_JOB_ID "$WORKDIR"


